[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_CONTEXT = "$CONTEXT"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[context.production.environment]
  REACT_APP_GREETING = "Hello"

